use std::error::Error as StdError;

fn main() -> Result<(), Box<dyn StdError>> {
    Ok(())
}
